### ISSUE TITLE
Improve the Elasticsearch integration with a Bulk index call

### ISSUE THREAD

**Issue by nfrankel** [hazelcast-demos/jet-elastic#6]

**Comment by dadoonet** [comment]
AFAICS it's done behind the scene. The only thing that I don't know is how often the Bulk API is called. Is it for every document or after a given number of documents?

I'll try to find this out.

**Comment by nfrankel** [comment]
In order to limit the number of HTTP requests, Jet buffers the items until it reaches a specific queue size. Once that is reached, it will call the Bulk API will all buffered items.

By default, the queue size is 1024. You can set it using the `queueSize` property of the `edgeConfig` attribute:

```yaml
hazelcast-jet:
  edge-defaults:
    queue-size: 1024
```

**Comment by dadoonet** [comment]
Amazing. Closing the issue then 😉
